---

- name: Bootstrap systems after clean install
  hosts: pfc
  user: root
  roles: 
#    - update
#    - repos
#    - xfce
#    - dev
#    - packages
#    - selinux
#    - ntp
#    - autofs
    - ldap
    - gdm
#    - runlevel
