---

- name: Bootstrap systems after clean install
  hosts: pfc-remote
  user: root
  roles: 
#    - update
#    - repos
#    - xfce
#    - dev
#    - selinux
#    - ntp
    - packages
#    - autofs
#    - ldap

#    - gdm
#    - runlevel
