---
  - name: install default packages
    yum: name={{ item }} state=present
    with_items:
      - "gimp"
      - "R"

  - name: install expat compatability library
    command: yum -y install /home/jarrod/src/ansible/roles/packages/files/compat-expat1-1.95.8-10.el7.centos.x86_64.rpm
