---
  - name: install extra default packages
    yum: name={{ item }} state=present
    with_items:
      - "gimp"
      - "R"
      - "gsl"
      - "gsl-devel"
      - "http://192.168.0.2/rpms/compat-expat1-1.95.8-10.el7.centos.x86_64.rpm"
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
