---
  - name: install default packages
    yum: name={{ item }} state=present
    with_items:
      - "bash-completion"
      - "man-pages"
      - "evince"
      - "gedit"
      - "wget"
      - "@Fonts"
      - "@Multimedia"
      - "@printing-client"
      - "nfs-utils"
      - "net-tools"
      - "libreoffice-calc"
      - "libreoffice-core"
      - "libreoffice-draw"
      - "libreoffice-graphicfilter"
      - "libreoffice-impress"
      - "libreoffice-opensymbol-fonts"
      - "libreoffice-pdfimport"
      - "libreoffice-pyuno"
      - "libreoffice-ure"
      - "libreoffice-writer"
      - "libpng12"
      - "compat-libtiff3"
      - "compat-glibc-headers"
      - "compat-libgfortran-41"
      - "compat-gcc-44"
      - "compat-gcc-44-c++"
      - "compat-gcc-44-gfortran"
      - "compat-glibc"
      - "compat-libf2c-34"
      - "gnome-colors-icon-theme"
