---
  - name: install XFCE
    yum: name={{ item }} state=present
    with_items:
      - "Thunar"
      - "xfce4-panel"
      - "xfce4-session"
      - "xfce4-settings"
      - "xfconf"
      - "xfdesktop"
      - "xfwm4"
      - "gdm"
      - "openssh-askpass"
      - "polkit-gnome"
      - "xfce4-session-engines"
      - "xfce4-terminal"
      - "xfce4-screenshooter"

  - name: remove XFCE power manager
    yum: name={{ item }} state=absent
    with_items:
      - "xfce4-power-manager"

  - name: install screen lock
    yum: name="xscreensaver" state=latest
