---
  - name: install XFCE development environment
    yum: name="@xfce-desktop" state=present

  - name: install X
    yum: name="@X Window System" state=latest
    when: ansible_distribution == 'CentOS'

  - name: install XFCE extras
    yum: name={{ item }} state=present
    with_items:
      - "xfce4-terminal"
      - "xfce4-screenshooter"

  - name: remove XFCE power manager
    yum: name={{ item }} state=absent
    with_items:
      - "xfce4-power-manager"

  - name: install screen lock
    yum: name="xscreensaver" state=latest
