---

- name: ensure mount directory exists
  file: path=/r state=directory owner=root group=root mode=0755
 
- name: install autofs
  yum: name=autofs state=installed

- name: add line to auto.master
  lineinfile: >
    dest=/etc/auto.master
    line="/r /etc/auto.remote --timeout=180"
    insertafter=EOF
    state=present

- name: add auto.remote
  copy: >
    src=auto.remote
    dest=/etc/auto.remote
    owner=root
    group=root
    mode=0644
  notify: restart autofs

- name: ensure autofs is running and enabled at system start
  service: >
    name={{ autofs_daemon }}
    state=started
    enabled=yes

- name: retrieve the list of d0 home directories
  command: ls /r/d0
  register: home_d0

- name: add d0 home dirs to /home
  file: >
    src=/r/d0/{{ item }}
    dest=/home/{{ item }}
    state=link
  with_items: "{{ home_d0.stdout_lines }}"

- name: retrieve the list of d1 home directories
  command: ls /r/d1
  register: home_d1

- name: add d1 home dirs to /home
  file: >
    src=/r/d1/{{ item }}
    dest=/home/{{ item }}
    state=link
  with_items: "{{ home_d1.stdout_lines }}"
