---


- name: add fmri.sh to profile
  copy: >
    src=fmri.sh
    dest=/etc/profile.d/fmri.sh
    owner=root
    group=root
    mode=0644

- name: add hosts file
  copy: >
    src=hosts
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644
