- name: install NFS packages
  yum:
    name: 'nfs-utils'
    state: present

- name: Copy exports file.
  copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs

- name: ensure NFS started
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - 'nfs'
    - 'nfs-lock'
