# This playbook makes the RPMFusion (http://rpmfusion.org/) repository available.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the rpmfusion repo packages
  yum: name={{ item }}
       state=latest
  with_items:
    - kmod-wl
